In [1]:
import pandas as pd

titanic = pd.read_csv("titanic.csv")
df = pd.read_csv("titanic.csv")

titanic.shape

(891, 12)

In [2]:
titanic["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [3]:
titanic["Name"].str.split(",").head()

0                           [Braund,  Mr. Owen Harris]
1    [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                            [Heikkinen,  Miss. Laina]
3      [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                          [Allen,  Mr. William Henry]
Name: Name, dtype: object

In [4]:
titanic["Title"] = titanic["Name"].str.split(",").str[1].str.split(".").str[0].str.strip()
titanic["Title"].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [5]:
titanic.groupby("Title")["Survived"].agg(["mean", "count"])

                  mean  count
Title
Capt          0.000000      1
Col           0.500000      2
Don           0.000000      1
Dr            0.428571      7
Jonkheer      0.000000      1
Lady          1.000000      1
Major         0.500000      2
Master        0.575000     40
Miss          0.697802    182
Mlle          1.000000      2
Mme           1.000000      1
Mr            0.156673    517
Mrs           0.792000    125
Ms            1.000000      1
Rev           0.000000      6
Sir           1.000000      1
the Countess  1.000000      1

In [6]:
titanic["Title"] = titanic["Title"].replace({"Mlle": "Miss", "Ms": "Miss", "Mme": "Mrs"})

common = ["Mr", "Miss", "Mrs", "Master"]
titanic["Title"] = titanic["Title"].where(titanic["Title"].isin(common), "other")

titanic.groupby("Title")["Survived"].agg(["mean", "count"])

            mean  count
Title
Master  0.575000     40
Miss    0.702703    185
Mr      0.156673    517
Mrs     0.793651    126
other   0.347826     23

In [7]:
df.groupby(["Pclass", "Sex"])["Survived"].mean().unstack()          # Lesson 3

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [8]:
pd.crosstab(df["Pclass"], df["Sex"], values=df["Survived"], aggfunc="mean")   # Lesson 8

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [9]:
df.pivot_table(index="Pclass", columns="Sex", values="Survived", aggfunc="mean")

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [10]:
titanic.pivot_table(index="Pclass", columns="Sex", values="Survived",
                    aggfunc=["mean", "count"])

            mean            count
Sex       female      male female male
Pclass
1       0.968085  0.368852     94  122
2       0.921053  0.157407     76  108
3       0.500000  0.135447    144  347

In [11]:
titanic.pivot_table(index="Pclass", values=["Survived", "Fare", "Age"],
                    aggfunc="mean")

              Age       Fare  Survived
Pclass
1       38.233441  84.154687  0.629630
2       29.877630  20.662183  0.472826
3       25.140620  13.675550  0.242363

In [12]:
titanic.pivot_table(index="Pclass",
                    values=["Survived", "Fare"],
                    aggfunc={"Survived": "mean", "Fare": "median"})

           Fare  Survived
Pclass
1       60.2875  0.629630
2       14.2500  0.472826
3        8.0500  0.242363

In [13]:
titanic.pivot_table(index="Title", columns="Pclass", values="Survived", aggfunc="mean")

Pclass         1         2         3
Title
Master  1.000000  1.000000  0.392857
Miss    0.958333  0.942857  0.500000
Mr      0.345794  0.087912  0.112853
Mrs     0.976744  0.902439  0.500000
other   0.533333  0.000000       NaN